---
kind: pipeline
type: kubernetes
name: OpsData-amd64

platform:
  os: linux
  arch: amd64

steps:

  - name: Go-Build-API
    image: golang
    environment:
      CGO_ENABLED: 0
    commands:
      - cd ./api/
      - go get
      - go build -o main
    resources:
      limits:
        cpu: 2000
        memory: 4000MiB
      requests:
        cpu: 1000
        memory: 2000MiB

  - name: Docker-Build-API
    image: plugins/docker
    settings:
      purge: false
      registry: registry.support.tools
      repo: registry.support.tools/opsdata/api
      dockerfile: ./api/Dockerfile
      context: ./api/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "registry.support.tools/opsdata/api:latest"
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      depends_on:
        - Go-Build-API

  - name: Docker-Build-UI
    image: plugins/docker
    settings:
      purge: false
      registry: registry.support.tools
      repo: registry.support.tools/opsdata/ui
      dockerfile: ./ui/Dockerfile
      context: ./ui/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "registry.support.tools/opsdata/ui:latest"
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password

  - name: Customize-kube-files
    image: supporttools/kube-builder:32
    environment:
      APPENV: ${DRONE_COMMIT_BRANCH}
      JWT:
        from_secret: jwt-secret-key
    commands:
      - bash ./k8s/deploy.sh
    depends_on:
      - Docker-Build-API
      - Docker-Build-UI

  - name: Deploy-to-User
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - REPO_USER=`echo ${DRONE_REPO} | awk -F'/' '{print $1}'`
      - kubectl create ns opsdata-${REPO_USER}
      - kubectl label ns opsdata-${REPO_USER} team=opsdata
      - kubectl label ns opsdata-${REPO_USER} app=opsdata
      - kubectl label ns opsdata-${REPO_USER} ns-purge=true
      - kubectl label ns opsdata-${REPO_USER} class=master
      - kubectl annotate ns opsdata-${REPO_USER} field.cattle.io/projectId=c-hq794:p-m4pgb  
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-${REPO_USER} --history-max 2 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/ingress/dev.yaml
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/hpa/dev.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-dev.yaml
      - kubectl wait -n opsdata-${REPO_USER}  --for=condition=available --timeout=600s deployment/opsdata-api
      - kubectl wait -n opsdata-${REPO_USER}  --for=condition=available --timeout=600s deployment/opsdata-ui
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Dev
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-dev --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl apply -n opsdata-dev -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-dev -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-dev -f ./k8s/ingress/dev.yaml
      - kubectl apply -n opsdata-dev -f ./k8s/hpa/dev.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-dev.yaml
      - kubectl wait -n opsdata-dev --for=condition=available --timeout=600s deployment/opsdata-api
      - kubectl wait -n opsdata-dev --for=condition=available --timeout=600s deployment/opsdata-ui
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Staging
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
      JWT:
        from_secret: jwt-secret-key
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-staging --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl -n opsdata-staging create secret generic jwt-secret-key --from-literal=jwt-secret-key=${JWT} -o yaml --dry-run | kubectl apply -f -
      - kubectl apply -n opsdata-staging -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-staging -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-staging -f ./k8s/ingress/staging.yaml
      - kubectl apply -n opsdata-staging -f ./k8s/hpa/staging.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-staging.yaml
      - kubectl wait -n opsdata-staging --for=condition=available --timeout=600s deployment/opsdata
    when:
     event:
     - deployment
     - promote
     target:
     - staging
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Production
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: b1-k3s-prd_server
      kubernetes_token:
        from_secret: b1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
      JWT:
        from_secret: jwt-secret-key
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-production --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl -n opsdata-production create secret generic jwt-secret-key --from-literal=jwt-secret-key=${JWT}
      - kubectl apply -n opsdata-production -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-production -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-production -f ./k8s/ingress/production-root.yaml
      - kubectl apply -n opsdata-production -f ./k8s/ingress/production-www.yaml
      - kubectl apply -n opsdata-production -f ./k8s/hpa/production.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-production.yaml
      - kubectl wait -n opsdata-production --for=condition=available --timeout=600s deployment/opsdata
    when:
     event:
     - deployment
     - promote
     target:
     - production
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Disaster
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
      JWT:
        from_secret: jwt-secret-key
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-disaster --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl -n opsdata-disaster create secret generic jwt-secret-key --from-literal=jwt-secret-key=${JWT}
      - kubectl apply -n opsdata-disaster -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-disaster -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-disaster -f ./k8s/ingress/disaster-root.yaml
      - kubectl apply -n opsdata-disaster -f ./k8s/ingress/disaster-www.yaml
      - kubectl apply -n opsdata-disaster -f ./k8s/hpa/disaster.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-disaster.yaml
      - kubectl wait -n opsdata-disaster --for=condition=available --timeout=600s deployment/opsdata
    when:
     event:
     - deployment
     - promote
     target:
     - production
    depends_on:
      - Deploy-to-Production

node_selector:
  beta.kubernetes.io/arch: amd64
  drone-runner: true

image_pull_secrets:
- regcreds

---
kind: pipeline
type: kubernetes
name: OpsData-arm64

platform:
  os: linux
  arch: arm64

steps:

  - name: Go-Build-API
    image: golang
    environment:
      CGO_ENABLED: 0
    commands:
      - cd ./api/
      - go get
      - go build -o main
    resources:
      limits:
        cpu: 2000
        memory: 4000MiB
      requests:
        cpu: 1000
        memory: 2000MiB

  - name: Docker-Build-API
    image: plugins/docker
    settings:
      purge: false
      registry: registry.support.tools
      repo: registry.support.tools/opsdata/api
      dockerfile: ./api/Dockerfile
      context: ./api/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "registry.support.tools/opsdata/api:latest"
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
      depends_on:
        - Go-Build-API

  - name: Docker-Build-UI
    image: plugins/docker
    settings:
      purge: false
      registry: registry.support.tools
      repo: registry.support.tools/opsdata/ui
      dockerfile: ./ui/Dockerfile
      context: ./ui/
      tags:
        - ${DRONE_BUILD_NUMBER}
        - ${DRONE_COMMIT_BRANCH}
        - latest
      cache_from: "registry.support.tools/opsdata/ui:latest"
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password

  - name: Customize-kube-files
    image: supporttools/kube-builder:32
    environment:
      APPENV: ${DRONE_COMMIT_BRANCH}
      JWT:
        from_secret: jwt-secret-key
    commands:
      - bash ./k8s/deploy.sh
    depends_on:
      - Docker-Build-API
      - Docker-Build-UI

  - name: Deploy-to-User
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - REPO_USER=`echo ${DRONE_REPO} | awk -F'/' '{print $1}'`
      - kubectl create ns opsdata-${REPO_USER}
      - kubectl label ns opsdata-${REPO_USER} team=opsdata
      - kubectl label ns opsdata-${REPO_USER} app=opsdata
      - kubectl label ns opsdata-${REPO_USER} ns-purge=true
      - kubectl label ns opsdata-${REPO_USER} class=master
      - kubectl annotate ns opsdata-${REPO_USER} field.cattle.io/projectId=c-hq794:p-m4pgb  
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-${REPO_USER} --history-max 2 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/ingress/dev.yaml
      - kubectl apply -n opsdata-${REPO_USER}  -f ./k8s/hpa/dev.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-dev.yaml
      - kubectl wait -n opsdata-${REPO_USER}  --for=condition=available --timeout=600s deployment/opsdata-api
      - kubectl wait -n opsdata-${REPO_USER}  --for=condition=available --timeout=600s deployment/opsdata-ui
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Dev
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-dev --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl apply -n opsdata-dev -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-dev -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-dev -f ./k8s/ingress/dev.yaml
      - kubectl apply -n opsdata-dev -f ./k8s/hpa/dev.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-dev.yaml
      - kubectl wait -n opsdata-dev --for=condition=available --timeout=600s deployment/opsdata-api
      - kubectl wait -n opsdata-dev --for=condition=available --timeout=600s deployment/opsdata-ui
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Staging
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
      JWT:
        from_secret: jwt-secret-key
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-staging --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl -n opsdata-staging create secret generic jwt-secret-key --from-literal=jwt-secret-key=${JWT} -o yaml --dry-run | kubectl apply -f -
      - kubectl apply -n opsdata-staging -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-staging -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-staging -f ./k8s/ingress/staging.yaml
      - kubectl apply -n opsdata-staging -f ./k8s/hpa/staging.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-staging.yaml
      - kubectl wait -n opsdata-staging --for=condition=available --timeout=600s deployment/opsdata
    when:
     event:
     - deployment
     - promote
     target:
     - staging
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Production
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: b1-k3s-prd_server
      kubernetes_token:
        from_secret: b1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
      JWT:
        from_secret: jwt-secret-key
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-production --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl -n opsdata-production create secret generic jwt-secret-key --from-literal=jwt-secret-key=${JWT}
      - kubectl apply -n opsdata-production -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-production -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-production -f ./k8s/ingress/production-root.yaml
      - kubectl apply -n opsdata-production -f ./k8s/ingress/production-www.yaml
      - kubectl apply -n opsdata-production -f ./k8s/hpa/production.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-production.yaml
      - kubectl wait -n opsdata-production --for=condition=available --timeout=600s deployment/opsdata
    when:
     event:
     - deployment
     - promote
     target:
     - production
    depends_on:
      - Customize-kube-files

  - name: Deploy-to-Disaster
    image: supporttools/kube-builder:32
    settings:
      kubernetes_server:
        from_secret: a1-k3s-prd_server
      kubernetes_token:
        from_secret: a1-k3s-prd_token
    environment:
      PASSWORD:
        from_secret: registry-password
      USERNAME:
        from_secret: registry-username
      JWT:
        from_secret: jwt-secret-key
    commands:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm upgrade --install opsdata --namespace opsdata-disaster --history-max 3 -f ./helm-config-ready/mariadb-galera/values.yaml bitnami/mariadb-galera
      - kubectl -n opsdata-disaster create secret generic jwt-secret-key --from-literal=jwt-secret-key=${JWT}
      - kubectl apply -n opsdata-disaster -f ./k8s/deployment-ready/
      - kubectl apply -n opsdata-disaster -f ./k8s/services/service.yaml
      - kubectl apply -n opsdata-disaster -f ./k8s/ingress/disaster-root.yaml
      - kubectl apply -n opsdata-disaster -f ./k8s/ingress/disaster-www.yaml
      - kubectl apply -n opsdata-disaster -f ./k8s/hpa/disaster.yaml
      - kubectl apply -n monitoring -f ./k8s/monitoring/servicemonitor-disaster.yaml
      - kubectl wait -n opsdata-disaster --for=condition=available --timeout=600s deployment/opsdata
    when:
     event:
     - deployment
     - promote
     target:
     - production
    depends_on:
      - Deploy-to-Production

node_selector:
  beta.kubernetes.io/arch: arm64
  drone-runner: true

image_pull_secrets:
- regcreds
