apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: opsdata
  annotations:
    external-dns.alpha.kubernetes.io/hostname: REPO_USER.opsdata.io
    external-dns.alpha.kubernetes.io/ttl: "120"
  name: lb
spec:
  rules:
  - host: REPO_USER.opsdata.io
    http:
      paths:
      - backend:
          serviceName: opsdata-ui
          servicePort: 80
        pathType: ImplementationSpecific
      - backend:
          serviceName: opsdata-api
          servicePort: 8000
        path: /api
        pathType: ImplementationSpecific