---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsdata
spec:
  selector:
    matchLabels:
      app: opsdata
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opsdata
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      containers:
      - env:
        - name: site
          value: opsdata
        image: registry.support.tools/opsdata/opsdata:BUILD_NUMBER
        imagePullPolicy: IfNotPresent
        name: opsdata
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2
