apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: opsdata
  annotations:
    external-dns.alpha.kubernetes.io/hostname: www.opsdata.io
    external-dns.alpha.kubernetes.io/ttl: "120"
  name: production-www-lb
spec:
  rules:
  - host: www.opsdata.io
    http:
      paths:
      - backend:
          serviceName: opsdata
          servicePort: 8000
        pathType: ImplementationSpecific
