---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opsdata-api
  name: opsdata-api
spec:
  ports:
  - name: "http"
    port: 8000
    targetPort: 8000
  selector:
    app: opsdata-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opsdata-ui
  name: opsdata-ui
spec:
  ports:
  - name: "http"
    port: 3000
    targetPort: 3000
  selector:
    app: opsdata-ui
